# d8b  .d88888b. 88888888888     d8888 8888888b.
# Y8P d88P" "Y88b    888        d88888 888  "Y88b
#     888     888    888       d88P888 888    888
# 888 888     888    888      d88P 888 888    888  .d88b.  888  888 .d8888b
# 888 888     888    888     d88P  888 888    888 d8P  Y8b 888  888 88K
# 888 888     888    888    d88P   888 888    888 88888888 Y88  88P "Y8888b.
# 888 Y88b. .d88P    888   d8888888888 888  .d88P Y8b.      Y8bd8P       X88
# 888  "Y88888P"     888  d88P     888 8888888P"   "Y8888    Y88P    88888P'
#
# Configuration File for Turrets plugin

# Plugin mode
# Values: - API // this will disable the ability for players to spawn turrets via the Glowing Obsidian block (useful for developers that want to integrate this plugin into other plugins)
#         - Standalone // Default mode
mode: "Standalone"

# How far should the entity / player be for the Turret to look at it
lookRadius: 15

# How far should the entity / player be for the Turret to shoot it
shootRadius: 10

# Shoot every `n` ticks
shootPerTick: 10